package.path = package.path .. ";../?.lua;../ntt/?.lua"
local testing = require("t").new()
local EntityPool = require("entity")
local ComponentStore = require("component")

testing:test("create new store", function ()
  local store = ComponentStore:new("Position")
  testing.assertNotNil(store, "Store should not be nil")
  testing.assertEqual("Position", store.name, "Store name should match")
end)

testing:test("isTag option", function()
  local store = ComponentStore:new("Collidable", { isTag = true })
  testing.assertEqual(true, store.isTag, "isTag should be true")
end)

testing:test("new with default option", function()
  local store = ComponentStore:new("Health", { default = { hp = 100, max = 100 } })
  testing.assertNotNil(store.default, "default should be set")
  testing.assertEqual(100, store.default.hp, "default hp should be 100")
end)

testing:test("add component to entity", function()
  local pool = EntityPool:new()
  local store = ComponentStore:new("TestComponent")
  local entity = pool:create()
  store:add(entity, { x = 10, y = 20 })
  testing.assertEqual(1, store.count, "Count should be 1 after adding")
end)

testing:test("returns component data", function()
  local pool = EntityPool:new()
  local store = ComponentStore:new("TestComponent")
  local entity = pool:create()
  store:add(entity, { x = 10, y = 20 })
  local data = store:get(entity) or {}
  testing.assertNotNil(data, "Data should not be nil")
  testing.assertEqual(10, data.x, "x should be 10")
  testing.assertEqual(20, data.y, "y should be 20")
end)

testing:test("has() returns true when entity has component", function()
  local pool = EntityPool:new()
  local store = ComponentStore:new("TestComponent")
  local entity = pool:create()
  store:add(entity, { value = 1 })
  testing.assertEqual(true, store:has(entity), "has should return true")
end)

testing:test("update existing component data", function()
  local pool = EntityPool:new()
  local store = ComponentStore:new("TestComponent")
  local entity = pool:create()
  store:add(entity, { x = 10 })
  store:add(entity, { x = 99 })
  testing.assertEqual(99, store:get(entity).x, "x should be updated to 99")
end)

testing:test("remove component from entity", function()
  local pool = EntityPool:new()
  local store = ComponentStore:new("TestComponent")
  local entity = pool:create()
  store:add(entity, { x = 10 })
  testing.assertEqual(true, store:has(entity), "Entity should have component before remove")
  local result = store:remove(entity)
  testing.assertEqual(true, result, "remove should return true on success")
  testing.assertEqual(false, store:has(entity), "Entity should not have component after remove")
  testing.assertEqual(0, store.count, "Count should be 0 after remove")
end)

testing:report()
